name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v3
      - run: cargo test -- verbose

  win-test:
    name: Win-Test
    runs-on: windows-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v3
      - run: cargo test -- verbose

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  minimal:
    name: "Rust 1.60.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.60.0
      - run: cargo build --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
#    if: github.event_name != 'pull_request'
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy -- -Aclippy::style -Dclippy::perf -Dwarnings